import Header from 'components/header';
import Progress from 'components/progess';
import SideBar from 'components/sidebar';
import { initPreferences, prefsStore } from 'contexts/prefs';
import Head from 'next/head';
import { useEffect } from 'react';
import { Provider } from 'react-redux';
import styles from 'styles/Home.module.css';
import '../styles/globals.css';
import "@fontsource/inter/300.css";

export default function App({ Component, pageProps }) {
  
  useEffect(() => {
    if (typeof window !== undefined) {
      initPreferences();
    }
  }, []);

  return (
    <div className={styles.html}>
      <Head>
        <title>Foforum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={prefsStore}>
        <Header />
        <Progress />
        <div className={styles.body}>
          <SideBar />
          <div className={styles.app}>
            <Component {...pageProps} />
          </div>
        </div>
      </Provider>
    </div>
  );
}
